### ISSUE TITLE
Roadmap for Seed

### ISSUE THREAD

**Issue by NiChrosia** [NiChrosia/seed#1]
The overall goals for this project are to create a usable game framework, featuring rendering, entities, and UI.

Currently, the project is only focused on rendering, and will expand once that is mostly feature-complete.

## Rendering
- [ ] Construct a cleaner & more idiomatic GL API.
  - [X] Vertex arrays and buffers
  - [X] Shaders & shader programs
    - [X] Shader uniforms
  - [X] Textures
  - [ ] Matrix support
- [ ] Construct a more high-level layer of abstraction above the GL API
  - [ ] Texture atlases
  - [ ] Unified objects and data, like `Renderer` and `Batch`
